apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-ssm-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aws-ssm-operator
  template:
    metadata:
      labels:
        name: aws-ssm-operator
    spec:
      serviceAccountName: aws-ssm-operator
      containers:
        - name: aws-ssm-operator
          image: calebpalmer/ssmparameter-operator
          command:
          - aws-ssm-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "aws-ssm-operator"
            - name: AWS_REGION
              value: "ca-central-1"
            - name: AWS_ACCESS_KEY_ID
              value: "AKIAYR6GAC6E3NRSPHAL"
            - name: AWS_SECRET_ACCESS_KEY
              value: "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"
