{{- if .Values.operator.awsSecretAccessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aws-ssm-operator.name" . }}
  labels:
    {{- include "aws-ssm-operator.labels" . | nindent 4 }}
type: Opaque
data:
  awsSecretAccessKey: {{ .Values.operator.awsSecretAccessKey | b64enc }}
{{- end }}
